# Generated by Django 4.2.10 on 2024-02-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField()),
            ],
        ),
    ]
